services:
  - type: web
    name: orisia-client
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://orisia-api.onrender.com/api
