services:
  - type: web
    runtime: static
    name: orisia-client
    repo: https://github.com/viktor132607/Orisia.Client.git
    branch: main
    region: frankfurt
    autoDeployTrigger: checksPass
    buildCommand: npm ci && npm run build
    staticPublishPath: ./out
    envVars:
      - key: NEXT_PUBLIC_SITE_URL
        value: https://orisia-client.onrender.com
      - key: NEXT_PUBLIC_API_URL
        value: https://orisia-api.onrender.com/api
