"use client";

import { FormEvent, useEffect, useState } from "react";
import { api, type DanceResponse } from "../../../lib/api";
import useLanguage from "../../../components/useLanguage";

type F={id?:string;titleBg:string;titleEn:string;descriptionBg:string;descriptionEn:string;region:string;rhythm:string;videoUrl:string;durationSeconds:string;active:boolean};
const empty:F={titleBg:"",titleEn:"",descriptionBg:"",descriptionEn:"",region:"",rhythm:"",videoUrl:"",durationSeconds:"",active:true};
export default function HorotekaAdminPage(){
 const isBg=useLanguage()==="bg";const[items,setItems]=useState<DanceResponse[]>([]);const[form,setForm]=useState<F>(empty);const[error,setError]=useState("");
 const load=()=>api.dances.adminList().then(setItems).catch((e:Error)=>setError(e.message));useEffect(()=>{load();},[]);
 async function submit(e:FormEvent){e.preventDefault();const body={titleBg:form.titleBg,titleEn:form.titleEn||form.titleBg,descriptionBg:form.descriptionBg,descriptionEn:form.descriptionEn||form.descriptionBg,region:form.region||null,rhythm:form.rhythm||null,videoUrl:form.videoUrl||null,thumbnailMediaId:null,durationSeconds:form.durationSeconds?Number(form.durationSeconds):null,sortOrder:form.id?(items.find(x=>x.id===form.id)?.sortOrder??0):items.length,active:form.active};try{form.id?await api.dances.update(form.id,body):await api.dances.create(body);setForm(empty);await load();}catch(x){setError(x instanceof Error?x.message:"Error");}}
 const edit=(x:DanceResponse)=>setForm({id:x.id,titleBg:x.titleBg,titleEn:x.titleEn,descriptionBg:x.descriptionBg,descriptionEn:x.descriptionEn,region:x.region||"",rhythm:x.rhythm||"",videoUrl:x.videoUrl||"",durationSeconds:x.durationSeconds?.toString()||"",active:x.active});
 const input="min-h-11 w-full border border-orisia-line bg-white px-3 font-sans text-sm dark:border-[#604a39] dark:bg-[#130b07]";
 return <main className="bg-orisia-cream py-10 dark:bg-orisia-dark"><div className="mx-auto grid max-w-7xl gap-6 px-4 lg:grid-cols-[.9fr_1.1fr]"><form onSubmit={submit} className="border border-orisia-line bg-orisia-paper p-6 dark:bg-orisia-panel"><h1 className="text-3xl font-bold">{form.id?"Edit dance":(isBg?"Ново хоро":"New dance")}</h1><div className="mt-5 grid gap-3"><input className={input} required value={form.titleBg} onChange={e=>setForm({...form,titleBg:e.target.value})} placeholder="Title BG"/><input className={input} value={form.titleEn} onChange={e=>setForm({...form,titleEn:e.target.value})} placeholder="Title EN"/><textarea className={`${input} min-h-28 py-3`} required value={form.descriptionBg} onChange={e=>setForm({...form,descriptionBg:e.target.value})} placeholder="Description BG"/><textarea className={`${input} min-h-28 py-3`} value={form.descriptionEn} onChange={e=>setForm({...form,descriptionEn:e.target.value})} placeholder="Description EN"/><input className={input} value={form.region} onChange={e=>setForm({...form,region:e.target.value})} placeholder="Region"/><input className={input} value={form.rhythm} onChange={e=>setForm({...form,rhythm:e.target.value})} placeholder="Rhythm"/><input className={input} type="url" value={form.videoUrl} onChange={e=>setForm({...form,videoUrl:e.target.value})} placeholder="Video URL"/><input className={input} type="number" value={form.durationSeconds} onChange={e=>setForm({...form,durationSeconds:e.target.value})} placeholder="Duration seconds"/><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active</label><button className="bg-orisia-gold px-4 py-3 text-xs font-bold text-white">{form.id?"Save":"Create"}</button>{form.id&&<button type="button" onClick={()=>setForm(empty)}>Cancel</button>}{error&&<p className="text-red-700">{error}</p>}</div></form><section className="border border-orisia-line bg-orisia-paper p-6 dark:bg-orisia-panel"><h2 className="text-3xl font-bold">{isBg?"Хоротека":"Dance library"}</h2><div className="mt-5 grid gap-3">{items.map(x=><article key={x.id} className="border border-orisia-line p-4"><strong>{x.titleBg}</strong><p className="font-sans text-xs">{x.region} · {x.rhythm} · {x.active?"active":"inactive"}</p><div className="mt-2 flex gap-3 text-xs"><button onClick={()=>edit(x)}>Edit</button><button className="text-red-700" onClick={()=>{ if (confirm("Delete?")) void api.dances.delete(x.id).then(load).catch((e:Error)=>setError(e.message)); }}>Delete</button></div></article>)}</div></section></div></main>;
}
