"use client";

import { FormEvent, useState } from "react";
import { api } from "../../lib/api";
import useLanguage from "../../components/useLanguage";

export default function ContactPage() {
  const language = useLanguage(); const isBg = language === "bg"; const [status, setStatus] = useState<"idle"|"sending"|"sent"|"error">("idle");
  const input = "min-h-12 w-full rounded border border-white/30 bg-white/10 px-3 font-sans text-sm text-white placeholder:text-white/50 outline-none focus:border-[#f0a65e]";
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setStatus("sending"); const form = new FormData(event.currentTarget);
    try { await api.inquiries.submit({ name: form.get("name"), email: form.get("email"), phone: form.get("phone") || null, subject: form.get("subject"), message: form.get("message") }); event.currentTarget.reset(); setStatus("sent"); } catch { setStatus("error"); }
  }
  return <main className="min-h-screen bg-[#6b3218] text-white dark:bg-[#140c08]"><section className="px-4 py-20"><div className="mx-auto max-w-7xl"><header className="text-center"><h1 className="text-5xl font-bold uppercase sm:text-6xl">{isBg ? "Контакти" : "Contacts"}</h1><p className="mt-4 text-white/80">{isBg ? "Свържете се с нас" : "Get in touch with us"}</p></header><div className="mt-14 grid gap-8 lg:grid-cols-2"><section className="rounded-2xl bg-white/[.07] p-8"><h2 className="text-2xl font-bold text-[#f0a65e]">{isBg ? "Информация за контакт" : "Contact information"}</h2><address className="mt-6 not-italic leading-8 text-white/80">{isBg ? "гр. Русе, ул. Родина 80, на гърба на боулинг залата, Русе, България, 7000" : "80 Rodina St., behind the bowling hall, Ruse, Bulgaria, 7000"}</address><iframe className="mt-8 min-h-[300px] w-full rounded border-0" title="ORISIA map" src="https://www.google.com/maps?q=%D0%B3%D1%80.%20%D0%A0%D1%83%D1%81%D0%B5%2C%20%D1%83%D0%BB.%20%D0%A0%D0%BE%D0%B4%D0%B8%D0%BD%D0%B0%2080&output=embed" loading="lazy" /></section><form onSubmit={submit} className="rounded-2xl bg-white/[.07] p-8"><h2 className="text-2xl font-bold text-[#f0a65e]">{isBg ? "Изпрати запитване" : "Send an inquiry"}</h2><div className="mt-6 grid gap-4"><input className={input} name="name" required minLength={2} placeholder={isBg ? "Име" : "Name"} /><input className={input} name="email" type="email" required placeholder="Email" /><input className={input} name="phone" placeholder={isBg ? "Телефон (по желание)" : "Phone (optional)"} /><input className={input} name="subject" required minLength={3} placeholder={isBg ? "Тема" : "Subject"} /><textarea className={`${input} min-h-40 py-3`} name="message" required minLength={10} placeholder={isBg ? "Съобщение" : "Message"} /><button disabled={status==="sending"} className="rounded bg-[#f0a65e] px-5 py-3 font-sans text-xs font-black uppercase text-[#4a210f] disabled:opacity-60">{status==="sending" ? (isBg ? "Изпращане…" : "Sending…") : (isBg ? "Изпрати" : "Send")}</button>{status==="sent" && <p className="font-sans text-sm text-green-200">{isBg ? "Запитването е изпратено." : "Your inquiry has been sent."}</p>}{status==="error" && <p className="font-sans text-sm text-red-200">{isBg ? "Възникна грешка." : "Something went wrong."}</p>}</div></form></div></div></section></main>;
}
