"use client";

import useLanguage from "../../components/useLanguage";
const sizeClasses: Record<string,string> = { large: "md:col-span-2 md:row-span-2", medium: "md:col-span-2", wide: "md:col-span-2", small: "" };

export default function GalleryPage() {
  const language=useLanguage(); const isBg=language==="bg";
  const galleryItems=[{title:isBg?"Сценични участия":"Stage performances",subtitle:isBg?"ОРИСИЯ на сцена":"ORISIA on stage",size:"large"},{title:isBg?"Фолклорни вечери":"Folklore evenings",subtitle:isBg?"Традиция и атмосфера":"Tradition and atmosphere",size:"medium"},{title:isBg?"Репетиции":"Rehearsals",subtitle:isBg?"Подготовка зад сцената":"Behind-the-scenes preparation",size:"small"},{title:isBg?"Събори":"Folklore gatherings",subtitle:isBg?"Български празници":"Bulgarian celebrations",size:"small"},{title:isBg?"Зад кулисите":"Behind the scenes",subtitle:isBg?"Моменти от подготовката":"Moments from the preparation",size:"small"},{title:isBg?"Специални събития":"Special events",subtitle:isBg?"Гостувания и участия":"Guest appearances and performances",size:"wide"},{title:"ОРИСИЯ",subtitle:isBg?"Хората зад танца":"The people behind the dance",size:"small"}];
  return <main className="bg-orisia-cream dark:bg-orisia-dark"><section className="border-b border-orisia-line bg-[#e8d5bb] py-14 dark:border-[#574333] dark:bg-[#1a100a]"><div className="mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8"><span className="font-sans text-[10px] font-black uppercase tracking-[.2em] text-orisia-goldDark">{isBg?"ОРИСИЯ · ГАЛЕРИЯ":"ORISIA · GALLERY"}</span><h1 className="mt-2 text-5xl font-bold sm:text-7xl">{isBg?"Галерия":"Gallery"}</h1><p className="mt-3 font-sans text-base text-[#725b47] dark:text-[#c6a77d]">{isBg?"Моменти от участия, репетиции, събори и фолклорни вечери.":"Moments from performances, rehearsals, folklore gatherings and folklore evenings."}</p></div></section><section className="py-12"><div className="mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-7 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><span className="font-sans text-[10px] font-black uppercase tracking-[.18em] text-orisia-goldDark">{isBg?"СНИМКИ":"PHOTOS"}</span><h2 className="mt-2 text-4xl font-bold">{isBg?"Моменти от ОРИСИЯ":"Moments from ORISIA"}</h2></div><p className="max-w-xl font-sans text-sm leading-6 text-[#725b47] dark:text-[#a98c69]">{isBg?"Страницата е подготвена за реалните снимки. Когато бъдат добавени изображенията, те ще влязат директно в този grid.":"The page is prepared for the real photos. Once images are added, they will appear directly in this grid."}</p></div><div className="grid auto-rows-[230px] gap-4 md:grid-cols-3">{galleryItems.map((item,index)=><article key={`${item.title}-${index}`} className={`group relative overflow-hidden border border-orisia-line bg-orisia-paper dark:border-[#604a39] dark:bg-orisia-panel ${sizeClasses[item.size]}`}><div className="grid h-full place-items-center bg-[#ead7ba] text-center dark:bg-[#28180f]"><div><strong className="block text-xl">{isBg?`Снимка ${index+1}`:`Photo ${index+1}`}</strong><span className="mt-1 block font-sans text-[10px] uppercase tracking-wide text-[#8b7156] dark:text-[#a58d71]">{isBg?"очаква изображение":"image pending"}</span></div></div><div className="absolute inset-x-0 bottom-0 bg-orisia-ink/90 p-4 text-orisia-light"><strong className="block text-lg">{item.title}</strong><span className="font-sans text-xs text-[#cbb79e]">{item.subtitle}</span></div></article>)}</div><div className="mt-5 border border-dashed border-orisia-line p-4 font-sans text-xs text-[#806a55] dark:border-[#604a39] dark:text-[#8f7658]">{isBg?"Галерията в момента използва placeholder-и, за да не се показват случайни или несвързани изображения.":"The gallery currently uses placeholders so random or unrelated images are not shown."}</div></div></section></main>;
}
