"use client";

import Link from "next/link";
import useLanguage, { useLocalizedPath } from "../../../components/useLanguage";
import { absoluteMediaUrl, type DanceResponse } from "../../../lib/api";

export default function DanceDetailClient({ dance }: { dance: DanceResponse }) {
  const language = useLanguage(); const isBg = language === "bg"; const href = useLocalizedPath();
  const title = isBg ? dance.titleBg : dance.titleEn || dance.titleBg;
  const description = isBg ? dance.descriptionBg : dance.descriptionEn || dance.descriptionBg;
  return <main className="bg-orisia-cream text-orisia-brown dark:bg-orisia-dark dark:text-orisia-light"><header className="border-b border-orisia-line bg-[#e8d5bb] py-14 dark:bg-[#1a100a]"><div className="mx-auto max-w-5xl px-4"><Link href={href("/horoteka/")} className="font-sans text-xs font-bold text-orisia-goldDark">← {isBg ? "Хоротека" : "Dance Library"}</Link><span className="mt-5 block font-sans text-[10px] font-black uppercase text-orisia-goldDark">{dance.region || (isBg ? "България" : "Bulgaria")} {dance.rhythm ? `· ${dance.rhythm}` : ""}</span><h1 className="mt-2 text-5xl font-bold sm:text-7xl">{title}</h1><p className="mt-5 font-sans text-base leading-7 text-[#725b47]">{description}</p></div></header><section className="py-12"><div className="mx-auto grid max-w-5xl gap-6 px-4 lg:grid-cols-[1fr_360px]"><article className="border border-orisia-line bg-orisia-paper p-7 dark:border-[#604a39] dark:bg-orisia-panel"><h2 className="text-3xl font-bold">{title}</h2><dl className="mt-6 grid gap-4 font-sans sm:grid-cols-2"><div><dt className="text-[10px] font-black uppercase text-orisia-goldDark">{isBg ? "Фолклорна област" : "Region"}</dt><dd>{dance.region || "—"}</dd></div><div><dt className="text-[10px] font-black uppercase text-orisia-goldDark">{isBg ? "Ритъм" : "Rhythm"}</dt><dd>{dance.rhythm || "—"}</dd></div></dl></article><aside className="border border-orisia-line bg-[#ead7ba] p-6 dark:bg-[#28180f]">{dance.videoUrl ? <iframe className="aspect-video w-full border-0" src={dance.videoUrl} title={title} allowFullScreen loading="lazy" /> : dance.thumbnailUrl ? <img src={absoluteMediaUrl(dance.thumbnailUrl)} alt={title} className="aspect-video w-full object-cover" /> : <div className="grid aspect-video place-items-center text-center"><span className="text-4xl">▶</span><p className="mt-2 font-sans text-sm">{isBg ? "Видео предстои" : "Video coming soon"}</p></div>}</aside></div></section></main>;
}
