"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { api, clearSession, type UserResponse } from "../../lib/api";
import useLanguage from "../../components/useLanguage";

export default function Page() {
  const router = useRouter(); const isBg = useLanguage() === "bg"; const [user, setUser] = useState<UserResponse | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const input = "min-h-11 w-full border border-orisia-line bg-white px-3 font-sans text-sm dark:border-[#604a39] dark:bg-[#130b07]";
  useEffect(() => { api.auth.me().then(setUser).catch(() => { clearSession(); router.replace("/login/"); }); }, [router]);
  async function profile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const d = new FormData(event.currentTarget); try { const updated = await api.auth.updateMe({ names: String(d.get("names")), email: String(d.get("email")), phone: String(d.get("phone")) }); setUser(updated); setMessage(isBg ? "Профилът е обновен." : "Profile updated."); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Error"); } }
  async function password(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const d = new FormData(event.currentTarget); try { await api.auth.changePassword({ currentPassword: String(d.get("currentPassword")), newPassword: String(d.get("newPassword")) }); setMessage(isBg ? "Паролата е сменена. Влезте отново." : "Password changed. Sign in again."); clearSession(); setTimeout(() => router.push("/login/"), 500); } catch (e) { setError(e instanceof Error ? e.message : "Error"); } }
  async function deactivate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const d = new FormData(event.currentTarget); if (!confirm(isBg ? "Да деактивирам ли профила?" : "Deactivate account?")) return; try { await api.auth.deactivate(String(d.get("deactivatePassword"))); clearSession(); router.push("/"); } catch (e) { setError(e instanceof Error ? e.message : "Error"); } }
  if (!user) return <main className="grid min-h-[60vh] place-items-center"><p>Loading…</p></main>;
  return <main className="min-h-[65vh] bg-orisia-cream py-12 dark:bg-orisia-dark"><div className="mx-auto grid max-w-5xl gap-6 px-4 lg:grid-cols-2"><section className="border border-orisia-line bg-orisia-paper p-7 dark:bg-orisia-panel"><h1 className="text-3xl font-bold">{isBg ? "Профил" : "Profile"}</h1><p className="mt-2 font-sans text-xs text-orisia-goldDark">{user.role}</p><form onSubmit={profile} className="mt-6 grid gap-3"><input name="names" defaultValue={user.names} required className={input} /><input name="email" defaultValue={user.email} type="email" required className={input} /><input name="phone" defaultValue={user.phone} required className={input} /><button className="bg-orisia-gold px-4 py-3 font-sans text-xs font-black uppercase text-white">{isBg ? "Запази" : "Save"}</button></form><button onClick={() => api.auth.logout().finally(() => router.push("/"))} className="mt-4 border border-orisia-line px-4 py-2 font-sans text-xs font-bold">{isBg ? "Изход" : "Logout"}</button></section><section className="grid gap-6"><div className="border border-orisia-line bg-orisia-paper p-7 dark:bg-orisia-panel"><h2 className="text-2xl font-bold">{isBg ? "Смяна на парола" : "Change password"}</h2><form onSubmit={password} className="mt-5 grid gap-3"><input name="currentPassword" type="password" required className={input} placeholder={isBg ? "Текуща парола" : "Current password"} /><input name="newPassword" type="password" minLength={8} required className={input} placeholder={isBg ? "Нова парола" : "New password"} /><button className="border border-orisia-goldDark px-4 py-3 font-sans text-xs font-black uppercase text-orisia-goldDark">{isBg ? "Смени" : "Change"}</button></form></div>{user.role !== "Admin" && <div className="border border-red-300 bg-red-50 p-7 dark:bg-red-950/20"><h2 className="text-2xl font-bold">{isBg ? "Деактивиране" : "Deactivate account"}</h2><form onSubmit={deactivate} className="mt-4 grid gap-3"><input name="deactivatePassword" type="password" required className={input} placeholder={isBg ? "Потвърди с парола" : "Confirm with password"} /><button className="border border-red-600 px-4 py-3 font-sans text-xs font-black uppercase text-red-700">{isBg ? "Деактивирай" : "Deactivate"}</button></form></div>}</section>{message && <p className="lg:col-span-2 font-sans text-sm text-green-700">{message}</p>}{error && <p className="lg:col-span-2 font-sans text-sm text-red-700">{error}</p>}</div></main>;
}
